apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app: {{ .Values.name }}
    chart_name: {{ .Values.name }}
    chart_version: {{ .Values.image.tag }}

data:
  tac_plus-ng.cfg: |  
{{ .Files.Get "tac_plus-ng.cfg" | indent 4 }}
