apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret-env
  labels:
    app: {{ .Values.name }}
    chart_name: {{ .Values.name }}
    chart_version: {{ .Values.image.tag }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey | b64enc }}
