{{ if .Values.persistentVolumeLocal.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistentVolumeLocal.storageClassName }} 
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: {{ .Values.persistentVolumeLocal.volumeBindingMode }}
{{- end }}
